#ifndef COLOR_FADING_CONSTANTS_H
#define COLOR_FADING_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, ColorFadingEffect) {
    COLOR_FADING_NONE,
    COLOR_FADING_WHITE,
    COLOR_FADING_BLACK,
    COLOR_FADING_DOOR_WHITE,
    COLOR_FADING_DOOR_BLACK,
    COLOR_FADING_WHITE_KEEP_HUD,
    COLOR_FADING_BLACK_KEEP_HUD,
    COLOR_FADING_BRIGHTNESS_WHITE, // Unused?
    COLOR_FADING_BRIGHTNESS_BLACK, // Unused?
    COLOR_FADING_ESCAPE_FAILED,
    COLOR_FADING_LAB_ESCAPE,

    COLOR_FADING_SA_X_ELEVATOR = 12,
    COLOR_FADING_WINDOW,
    COLOR_FADING_DEMO_END_INPUT,

    COLOR_FADING_DEMO_END_AUTO = 16,

    COLOR_FADING_FINAL_ESCAPE = 18,
    COLOR_FADING_MONO_WHITE,
    COLOR_FADING_MONO_BLACK,
};

#define COLOR_FADING_WHITE_FLAG 1

MAKE_ENUM(u8, ColorFadingSpeed) {
    COLOR_FADING_SPEED_FASTER,
    COLOR_FADING_SPEED_FAST,
    COLOR_FADING_SPEED_NORMAL,
    COLOR_FADING_SPEED_SLOW,

    COLOR_FADING_SPEED_COUNT
};

MAKE_ENUM(u8, MonochromeFading) {
    MONOCHROME_FADING_NONE,
    MONOCHROME_FADING_BLACK,
    MONOCHROME_FADING_WHITE,

    MONOCHROME_FADING_ACTIVE = 1 << 7,
    MONOCHROME_FADING_ENDED = UCHAR_MAX
};

MAKE_ENUM(u8, ColorFadingStatus) ENUM_FLAG {
    COLOR_FADING_STATUS_ON_BG =  1 << 0,
    COLOR_FADING_STATUS_ON_OBJ = 1 << 1
};

#endif /* COLOR_FADING_CONSTANTS_H */
